apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-version
data:
  VER_IMAGE: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
  VER_COMMIT: "{{ .Values.version.commit }}"
  VER_BRANCH: "{{ .Values.version.branch }}"
