apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: Astro{{ include "aws.env" . }}ApiRdsSecrets
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: db-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: db-secret
