apiVersion: v1
kind: Service
metadata:
  name: {{ include "astro-api.fullname" . }}
  labels:
    {{- include "astro-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: api
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "astro-api.selectorLabels" . | nindent 4 }}
