name: 'Helm Deploy'
runs:
  using: 'composite'
  steps:
  - name: helm deploy
    uses: koslib/helm-eks-action@v1.8.0
    with:
      command: |
        export CHART_FOLDER=apps/${APP_NAME}/deployment/app-chart
        helm lint $CHART_FOLDER
        helm template sputnik-v2-$APP_NAME $CHART_FOLDER \
          --set image.tag=$DOCKER_ENV_TAG \
          --set environment.near_env=$NEAR_ENV \
          --set environment.near_contract_name=$NEAR_CONTRACT_NAME \
          --set environment.near_token_factory_contract_name=$NEAR_TOKEN_FACTORY_CONTRACT_NAME \
          --set environment.near_bridge_token_factory_contract_name=$NEAR_BRIDGE_TOKEN_FACTORY_CONTRACT_NAME \
          --set environment.wallet_callback_url=$WALLET_CALLBACK_URL \
          --set environment.frontend_url=$FRONTEND_URL \
          --set environment.datadog_env=$DATADOG_ENV \
          --set ingress.host=$K8S_INGRESS_HOST

