export enum FeatureFlags {
  OpenSearchProposalIndexing = 'open-search-proposal-indexing',
  OpenSearchDaoIndexing = 'open-search-dao-indexing',
  OpenSearchBountyIndexing = 'open-search-bounty-indexing',
  OpenSearchDraftProposalIndexing = 'open-search-draft-proposal-indexing',
  DaoSettingsDynamo = 'dao-settings-dynamo',
  DaoDynamo = 'dao-dynamo',
  BountyDynamo = 'bounty-dynamo',
  ProposalDynamo = 'proposal-dynamo',
  TokenDynamo = 'token-dynamo',
  DaoStatsDynamo = 'dao-stats-dynamo',
  DraftCommentsDynamo = 'draft-comments-dynamo',
  DraftDynamo = 'draft-dynamo',
  NftTokenDynamo = 'nft-token-dynamo',
  NotificationDynamo = 'notification-dynamo',
  ErrorDynamo = 'error-dynamo',
}
