export enum DynamoEntityType {
  Dao = 'Dao',
  Proposal = 'Proposal',
  Bounty = 'Bounty',
  Account = 'Account',
  AccountNotification = 'AccountNotification',
  AccountNotificationSettings = 'AccountNotificationSettings',
  ProposalComment = 'ProposalComment',
  BountyComment = 'BountyComment',
  DraftProposalComment = 'DraftProposalComment',
  DraftProposal = 'DraftProposal',
  Notification = 'Notification',
  ProposalTemplate = 'ProposalTemplate',
  SharedProposalTemplate = 'SharedProposalTemplate',
  DaoStats = 'DaoStats',
  Subscription = 'Subscription',
  Nft = 'Nft',
  TokenBalance = 'TokenBalance',
  ScheduledProposalExpirationEvent = 'ScheduledProposalExpirationEvent',
}
