export enum DynamoEntityType {
  Dao = 'Dao',
  DaoIds = 'DAO_IDS',
  Proposal = 'Proposal',
  Bounty = 'Bounty',
  Account = 'Account',
  AccountNotification = 'AccountNotification',
  AccountNotificationIds = 'AccountNotificationIds',
  AccountNotificationSettings = 'AccountNotificationSettings',
  ProposalComment = 'ProposalComment',
  BountyComment = 'BountyComment',
  DraftProposalComment = 'DraftProposalComment',
  DraftProposal = 'DraftProposal',
  Notification = 'Notification',
  ProposalTemplate = 'ProposalTemplate',
  SharedProposalTemplate = 'SharedProposalTemplate',
  DaoStats = 'DaoStats',
  Subscription = 'Subscription',
  Nft = 'Nft',
  TokenBalance = 'TokenBalance',
  TokenPrice = 'TokenPrice',
  ScheduledProposalExpirationEvent = 'ScheduledProposalExpirationEvent',
  HandledReceiptAction = 'HandledReceiptAction',
  Otp = 'Otp',
  Error = 'Error',
  ErrorIds = 'ERROR_IDS',
}
