apiVersion: v1
kind: ConfigMap
metadata:
  name: sputnik-v2-draft-configmap
data:
  NODE_OPTIONS: ' --max-old-space-size={{ include "node.maxOldSpaceSize" . }} '
  PORT: "3000"
  NEST_APP_TYPE: draft
  REDIS_HTTP_CACHE_TTL: "60"
{{- range $k, $v := .Values.environment }}
  {{ $k }}: "{{ $v }}"
{{- end }}
