apiVersion: v1
kind: ConfigMap
metadata:
  name: sputnik-v2-draft-configmap
data:
  NODE_OPTIONS: ' --max-old-space-size={{ include "node.maxOldSpaceSize" . }} '
  PORT: "3000"
  NEST_APP_TYPE: draft
  REDIS_HTTP_CACHE_TTL: "60"
  WALLET_CALLBACK_URL: "{{ .Values.environment.wallet_callback_url }}"
  FRONTEND_URL: "{{ .Values.environment.frontend_url }}"
  API_RATE_TTL: "{{ .Values.environment.api_rate_ttl }}"
  API_RATE_LIMIT: "{{ .Values.environment.api_rate_limit }}"
  ADMIN_ACCOUNTS: "{{ .Values.environment.admin_accounts }}"
  NOTIFI_ENV: "{{ .Values.environment.notifi_env }}"
  NOTIFI_SID: "{{ .Values.environment.notifi_sid }}"
  NOTIFI_SECRET: "{{ .Values.environment.notifi_secret }}"
  NOTIFI_PREFIX: "{{ .Values.environment.notifi_prefix }}"
