apiVersion: v1
kind: Service
metadata:
  name: {{ include "sputnik-v2-draft.fullname" . }}
  labels:
    {{- include "sputnik-v2-draft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: api
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "sputnik-v2-draft.selectorLabels" . | nindent 4 }}
