export enum NotificationType {
  CustomDaoCreation = 'CustomDaoCreation',
  ClubDaoCreation = 'ClubDaoCreation',
  FoundationDaoCreation = 'FoundationDaoCreation',
  CorporationDaoCreation = 'CorporationDaoCreation',
  CooperativeDaoCreation = 'CooperativeDaoCreation',

  TransferProposalCreation = 'TransferProposalCreation',
  BountyProposalCreation = 'BountyProposalCreation',
  BountyDoneProposalCreation = 'BountyDoneProposalCreation',
  PollProposalCreation = 'PollProposalCreation',

  DaoNameUpdated = 'DaoNameUpdated',
  DaoPurposeUpdated = 'DaoPurposeUpdated',
  DaoLegalUpdated = 'DaoLegalUpdated',
  DaoLinksUpdated = 'DaoLinksUpdated',
  DaoFlagUpdated = 'DaoFlagUpdated',
  DaoDeadlinesUpdated = 'DaoDeadlinesUpdated',
  DaoRulesUpdated = 'DaoRulesUpdated',
  DaoGroupAdded = 'DaoGroupAdded',
  DaoGroupUpdated = 'DaoGroupUpdated',
  DaoGroupRemoved = 'DaoGroupRemoved',
  DaoMembersAdded = 'DaoMembersAdded',
  DaoMemberRemoved = 'DaoMemberRemoved',
}
