name: Test Aggregator
on:
  workflow_dispatch:
  pull_request:
    branches:
    - '**'
    paths:
    - 'apps/aggregator/**'
    - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
         echo SUBAPP_NAME=aggregator >> $GITHUB_ENV
         cat ".github/env.common" >>$GITHUB_ENV

    - name: Build Test
      uses: ./.github/actions/build-test
