apiVersion: v1
kind: ConfigMap
metadata:
  name: astro-notifier-configmap
data:
  NODE_OPTIONS: ' --max-old-space-size={{ include "node.maxOldSpaceSize" . }} '
  PORT: "3000"
  NEST_APP_TYPE: notifier
{{- range $k, $v := .Values.environment }}
  {{ $k }}: "{{ $v }}"
{{- end }}
