{{- if gt (int .Values.replicaCount) 1 -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notifier
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sputnik-v2-notifier
{{- end -}}
