apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sputnik-v2-aggregator.fullname" . }}
  labels:
    {{- include "sputnik-v2-aggregator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sputnik-v2-aggregator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sputnik-v2-aggregator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "sputnik-v2-aggregator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.internalPort }}
              protocol: TCP
          # TODO: Since we moved to TCP for aggregator microservice - need to use another apprroach for liveness probe
          # livenessProbe:
          #   httpGet:
          #     path: "{{ .Values.container.livenessProbe.path }}"
          #     port: {{ .Values.container.livenessProbe.port }}
          #     scheme: HTTP
          #   initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.container.livenessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.container.livenessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.container.livenessProbe.failureThreshold }}
          # readinessProbe:
          #   httpGet:
          #     path: "{{ .Values.container.readinessProbe.path }}"
          #     port: {{ .Values.container.readinessProbe.port }}
          #     scheme: HTTP
          #   initialDelaySeconds: {{ .Values.container.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.container.readinessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.container.readinessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.container.readinessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.container.readinessProbe.failureThreshold }}
          envFrom:
          - configMapRef:
              name: sputnik-v2-configmap
          - configMapRef:
              name: sputnik-v2-aggregator-configmap
          - configMapRef:
              name: {{ .Release.Name }}-version
          - secretRef:
              name: db-secret
          - secretRef:
              name: near-indexer-db-secret
          - secretRef:
              name: redis-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
