/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import api.app.astrodao.com.openapi.models.BountyClaim;
import api.app.astrodao.com.openapi.models.Dao;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Bounty
 */
@JsonPropertyOrder({
  Bounty.JSON_PROPERTY_TRANSACTION_HASH,
  Bounty.JSON_PROPERTY_UPDATE_TRANSACTION_HASH,
  Bounty.JSON_PROPERTY_CREATE_TIMESTAMP,
  Bounty.JSON_PROPERTY_UPDATE_TIMESTAMP,
  Bounty.JSON_PROPERTY_ID,
  Bounty.JSON_PROPERTY_BOUNTY_ID,
  Bounty.JSON_PROPERTY_DAO_ID,
  Bounty.JSON_PROPERTY_DAO,
  Bounty.JSON_PROPERTY_BOUNTY_CLAIMS,
  Bounty.JSON_PROPERTY_DESCRIPTION,
  Bounty.JSON_PROPERTY_TOKEN,
  Bounty.JSON_PROPERTY_AMOUNT,
  Bounty.JSON_PROPERTY_TIMES,
  Bounty.JSON_PROPERTY_MAX_DEADLINE,
  Bounty.JSON_PROPERTY_NUMBER_OF_CLAIMS
})
@JsonTypeName("Bounty")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class Bounty {
  public static final String JSON_PROPERTY_TRANSACTION_HASH = "transactionHash";
  private String transactionHash;

  public static final String JSON_PROPERTY_UPDATE_TRANSACTION_HASH = "updateTransactionHash";
  private String updateTransactionHash;

  public static final String JSON_PROPERTY_CREATE_TIMESTAMP = "createTimestamp";
  private BigDecimal createTimestamp;

  public static final String JSON_PROPERTY_UPDATE_TIMESTAMP = "updateTimestamp";
  private BigDecimal updateTimestamp;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_BOUNTY_ID = "bountyId";
  private BigDecimal bountyId;

  public static final String JSON_PROPERTY_DAO_ID = "daoId";
  private String daoId;

  public static final String JSON_PROPERTY_DAO = "dao";
  private Dao dao;

  public static final String JSON_PROPERTY_BOUNTY_CLAIMS = "bountyClaims";
  private List<BountyClaim> bountyClaims = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TOKEN = "token";
  private String token;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private String amount;

  public static final String JSON_PROPERTY_TIMES = "times";
  private String times;

  public static final String JSON_PROPERTY_MAX_DEADLINE = "maxDeadline";
  private String maxDeadline;

  public static final String JSON_PROPERTY_NUMBER_OF_CLAIMS = "numberOfClaims";
  private BigDecimal numberOfClaims;

  public Bounty() { 
  }

  public Bounty transactionHash(String transactionHash) {
    
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionHash() {
    return transactionHash;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  public Bounty updateTransactionHash(String updateTransactionHash) {
    
    this.updateTransactionHash = updateTransactionHash;
    return this;
  }

   /**
   * Get updateTransactionHash
   * @return updateTransactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdateTransactionHash() {
    return updateTransactionHash;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTransactionHash(String updateTransactionHash) {
    this.updateTransactionHash = updateTransactionHash;
  }


  public Bounty createTimestamp(BigDecimal createTimestamp) {
    
    this.createTimestamp = createTimestamp;
    return this;
  }

   /**
   * Get createTimestamp
   * @return createTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreateTimestamp() {
    return createTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateTimestamp(BigDecimal createTimestamp) {
    this.createTimestamp = createTimestamp;
  }


  public Bounty updateTimestamp(BigDecimal updateTimestamp) {
    
    this.updateTimestamp = updateTimestamp;
    return this;
  }

   /**
   * Get updateTimestamp
   * @return updateTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getUpdateTimestamp() {
    return updateTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTimestamp(BigDecimal updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
  }


  public Bounty id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Bounty bountyId(BigDecimal bountyId) {
    
    this.bountyId = bountyId;
    return this;
  }

   /**
   * Get bountyId
   * @return bountyId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOUNTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getBountyId() {
    return bountyId;
  }


  @JsonProperty(JSON_PROPERTY_BOUNTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBountyId(BigDecimal bountyId) {
    this.bountyId = bountyId;
  }


  public Bounty daoId(String daoId) {
    
    this.daoId = daoId;
    return this;
  }

   /**
   * Get daoId
   * @return daoId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDaoId() {
    return daoId;
  }


  @JsonProperty(JSON_PROPERTY_DAO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDaoId(String daoId) {
    this.daoId = daoId;
  }


  public Bounty dao(Dao dao) {
    
    this.dao = dao;
    return this;
  }

   /**
   * Get dao
   * @return dao
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Dao getDao() {
    return dao;
  }


  @JsonProperty(JSON_PROPERTY_DAO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDao(Dao dao) {
    this.dao = dao;
  }


  public Bounty bountyClaims(List<BountyClaim> bountyClaims) {
    
    this.bountyClaims = bountyClaims;
    return this;
  }

  public Bounty addBountyClaimsItem(BountyClaim bountyClaimsItem) {
    this.bountyClaims.add(bountyClaimsItem);
    return this;
  }

   /**
   * Get bountyClaims
   * @return bountyClaims
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOUNTY_CLAIMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BountyClaim> getBountyClaims() {
    return bountyClaims;
  }


  @JsonProperty(JSON_PROPERTY_BOUNTY_CLAIMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBountyClaims(List<BountyClaim> bountyClaims) {
    this.bountyClaims = bountyClaims;
  }


  public Bounty description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Bounty token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(String token) {
    this.token = token;
  }


  public Bounty amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(String amount) {
    this.amount = amount;
  }


  public Bounty times(String times) {
    
    this.times = times;
    return this;
  }

   /**
   * Get times
   * @return times
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTimes() {
    return times;
  }


  @JsonProperty(JSON_PROPERTY_TIMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimes(String times) {
    this.times = times;
  }


  public Bounty maxDeadline(String maxDeadline) {
    
    this.maxDeadline = maxDeadline;
    return this;
  }

   /**
   * Get maxDeadline
   * @return maxDeadline
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MAX_DEADLINE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMaxDeadline() {
    return maxDeadline;
  }


  @JsonProperty(JSON_PROPERTY_MAX_DEADLINE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxDeadline(String maxDeadline) {
    this.maxDeadline = maxDeadline;
  }


  public Bounty numberOfClaims(BigDecimal numberOfClaims) {
    
    this.numberOfClaims = numberOfClaims;
    return this;
  }

   /**
   * Get numberOfClaims
   * @return numberOfClaims
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_CLAIMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getNumberOfClaims() {
    return numberOfClaims;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_CLAIMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumberOfClaims(BigDecimal numberOfClaims) {
    this.numberOfClaims = numberOfClaims;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bounty bounty = (Bounty) o;
    return Objects.equals(this.transactionHash, bounty.transactionHash) &&
        Objects.equals(this.updateTransactionHash, bounty.updateTransactionHash) &&
        Objects.equals(this.createTimestamp, bounty.createTimestamp) &&
        Objects.equals(this.updateTimestamp, bounty.updateTimestamp) &&
        Objects.equals(this.id, bounty.id) &&
        Objects.equals(this.bountyId, bounty.bountyId) &&
        Objects.equals(this.daoId, bounty.daoId) &&
        Objects.equals(this.dao, bounty.dao) &&
        Objects.equals(this.bountyClaims, bounty.bountyClaims) &&
        Objects.equals(this.description, bounty.description) &&
        Objects.equals(this.token, bounty.token) &&
        Objects.equals(this.amount, bounty.amount) &&
        Objects.equals(this.times, bounty.times) &&
        Objects.equals(this.maxDeadline, bounty.maxDeadline) &&
        Objects.equals(this.numberOfClaims, bounty.numberOfClaims);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionHash, updateTransactionHash, createTimestamp, updateTimestamp, id, bountyId, daoId, dao, bountyClaims, description, token, amount, times, maxDeadline, numberOfClaims);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bounty {\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    updateTransactionHash: ").append(toIndentedString(updateTransactionHash)).append("\n");
    sb.append("    createTimestamp: ").append(toIndentedString(createTimestamp)).append("\n");
    sb.append("    updateTimestamp: ").append(toIndentedString(updateTimestamp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bountyId: ").append(toIndentedString(bountyId)).append("\n");
    sb.append("    daoId: ").append(toIndentedString(daoId)).append("\n");
    sb.append("    dao: ").append(toIndentedString(dao)).append("\n");
    sb.append("    bountyClaims: ").append(toIndentedString(bountyClaims)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    times: ").append(toIndentedString(times)).append("\n");
    sb.append("    maxDeadline: ").append(toIndentedString(maxDeadline)).append("\n");
    sb.append("    numberOfClaims: ").append(toIndentedString(numberOfClaims)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

