/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import api.app.astrodao.com.openapi.models.DaoConfig;
import api.app.astrodao.com.openapi.models.Policy;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DaoFeed
 */
@JsonPropertyOrder({
  DaoFeed.JSON_PROPERTY_TRANSACTION_HASH,
  DaoFeed.JSON_PROPERTY_UPDATE_TRANSACTION_HASH,
  DaoFeed.JSON_PROPERTY_CREATE_TIMESTAMP,
  DaoFeed.JSON_PROPERTY_UPDATE_TIMESTAMP,
  DaoFeed.JSON_PROPERTY_ID,
  DaoFeed.JSON_PROPERTY_CONFIG,
  DaoFeed.JSON_PROPERTY_METADATA,
  DaoFeed.JSON_PROPERTY_AMOUNT,
  DaoFeed.JSON_PROPERTY_TOTAL_SUPPLY,
  DaoFeed.JSON_PROPERTY_LAST_BOUNTY_ID,
  DaoFeed.JSON_PROPERTY_LAST_PROPOSAL_ID,
  DaoFeed.JSON_PROPERTY_STAKING_CONTRACT,
  DaoFeed.JSON_PROPERTY_NUMBER_OF_ASSOCIATES,
  DaoFeed.JSON_PROPERTY_NUMBER_OF_MEMBERS,
  DaoFeed.JSON_PROPERTY_COUNCIL,
  DaoFeed.JSON_PROPERTY_COUNCIL_SEATS,
  DaoFeed.JSON_PROPERTY_POLICY,
  DaoFeed.JSON_PROPERTY_CREATED_BY,
  DaoFeed.JSON_PROPERTY_TOTAL_PROPOSAL_COUNT,
  DaoFeed.JSON_PROPERTY_ACTIVE_PROPOSAL_COUNT,
  DaoFeed.JSON_PROPERTY_TOTAL_DAO_FUNDS
})
@JsonTypeName("DaoFeed")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class DaoFeed {
  public static final String JSON_PROPERTY_TRANSACTION_HASH = "transactionHash";
  private String transactionHash;

  public static final String JSON_PROPERTY_UPDATE_TRANSACTION_HASH = "updateTransactionHash";
  private String updateTransactionHash;

  public static final String JSON_PROPERTY_CREATE_TIMESTAMP = "createTimestamp";
  private BigDecimal createTimestamp;

  public static final String JSON_PROPERTY_UPDATE_TIMESTAMP = "updateTimestamp";
  private BigDecimal updateTimestamp;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CONFIG = "config";
  private DaoConfig config;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private String metadata;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private BigDecimal amount;

  public static final String JSON_PROPERTY_TOTAL_SUPPLY = "totalSupply";
  private String totalSupply;

  public static final String JSON_PROPERTY_LAST_BOUNTY_ID = "lastBountyId";
  private BigDecimal lastBountyId;

  public static final String JSON_PROPERTY_LAST_PROPOSAL_ID = "lastProposalId";
  private BigDecimal lastProposalId;

  public static final String JSON_PROPERTY_STAKING_CONTRACT = "stakingContract";
  private String stakingContract;

  public static final String JSON_PROPERTY_NUMBER_OF_ASSOCIATES = "numberOfAssociates";
  private BigDecimal numberOfAssociates;

  public static final String JSON_PROPERTY_NUMBER_OF_MEMBERS = "numberOfMembers";
  private BigDecimal numberOfMembers;

  public static final String JSON_PROPERTY_COUNCIL = "council";
  private List<String> council = new ArrayList<>();

  public static final String JSON_PROPERTY_COUNCIL_SEATS = "councilSeats";
  private BigDecimal councilSeats;

  public static final String JSON_PROPERTY_POLICY = "policy";
  private Policy policy;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  private String createdBy;

  public static final String JSON_PROPERTY_TOTAL_PROPOSAL_COUNT = "totalProposalCount";
  private BigDecimal totalProposalCount;

  public static final String JSON_PROPERTY_ACTIVE_PROPOSAL_COUNT = "activeProposalCount";
  private BigDecimal activeProposalCount;

  public static final String JSON_PROPERTY_TOTAL_DAO_FUNDS = "totalDaoFunds";
  private String totalDaoFunds;

  public DaoFeed() { 
  }

  public DaoFeed transactionHash(String transactionHash) {
    
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionHash() {
    return transactionHash;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  public DaoFeed updateTransactionHash(String updateTransactionHash) {
    
    this.updateTransactionHash = updateTransactionHash;
    return this;
  }

   /**
   * Get updateTransactionHash
   * @return updateTransactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdateTransactionHash() {
    return updateTransactionHash;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTransactionHash(String updateTransactionHash) {
    this.updateTransactionHash = updateTransactionHash;
  }


  public DaoFeed createTimestamp(BigDecimal createTimestamp) {
    
    this.createTimestamp = createTimestamp;
    return this;
  }

   /**
   * Get createTimestamp
   * @return createTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreateTimestamp() {
    return createTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateTimestamp(BigDecimal createTimestamp) {
    this.createTimestamp = createTimestamp;
  }


  public DaoFeed updateTimestamp(BigDecimal updateTimestamp) {
    
    this.updateTimestamp = updateTimestamp;
    return this;
  }

   /**
   * Get updateTimestamp
   * @return updateTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getUpdateTimestamp() {
    return updateTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTimestamp(BigDecimal updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
  }


  public DaoFeed id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public DaoFeed config(DaoConfig config) {
    
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DaoConfig getConfig() {
    return config;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfig(DaoConfig config) {
    this.config = config;
  }


  public DaoFeed metadata(String metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }


  public DaoFeed amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  public DaoFeed totalSupply(String totalSupply) {
    
    this.totalSupply = totalSupply;
    return this;
  }

   /**
   * Get totalSupply
   * @return totalSupply
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTotalSupply() {
    return totalSupply;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalSupply(String totalSupply) {
    this.totalSupply = totalSupply;
  }


  public DaoFeed lastBountyId(BigDecimal lastBountyId) {
    
    this.lastBountyId = lastBountyId;
    return this;
  }

   /**
   * Get lastBountyId
   * @return lastBountyId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LAST_BOUNTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getLastBountyId() {
    return lastBountyId;
  }


  @JsonProperty(JSON_PROPERTY_LAST_BOUNTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastBountyId(BigDecimal lastBountyId) {
    this.lastBountyId = lastBountyId;
  }


  public DaoFeed lastProposalId(BigDecimal lastProposalId) {
    
    this.lastProposalId = lastProposalId;
    return this;
  }

   /**
   * Get lastProposalId
   * @return lastProposalId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LAST_PROPOSAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getLastProposalId() {
    return lastProposalId;
  }


  @JsonProperty(JSON_PROPERTY_LAST_PROPOSAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastProposalId(BigDecimal lastProposalId) {
    this.lastProposalId = lastProposalId;
  }


  public DaoFeed stakingContract(String stakingContract) {
    
    this.stakingContract = stakingContract;
    return this;
  }

   /**
   * Get stakingContract
   * @return stakingContract
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STAKING_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStakingContract() {
    return stakingContract;
  }


  @JsonProperty(JSON_PROPERTY_STAKING_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStakingContract(String stakingContract) {
    this.stakingContract = stakingContract;
  }


  public DaoFeed numberOfAssociates(BigDecimal numberOfAssociates) {
    
    this.numberOfAssociates = numberOfAssociates;
    return this;
  }

   /**
   * How many accounts in total have interacted with the DAO (made proposals, voted, etc).
   * @return numberOfAssociates
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "How many accounts in total have interacted with the DAO (made proposals, voted, etc).")
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_ASSOCIATES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getNumberOfAssociates() {
    return numberOfAssociates;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_ASSOCIATES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumberOfAssociates(BigDecimal numberOfAssociates) {
    this.numberOfAssociates = numberOfAssociates;
  }


  public DaoFeed numberOfMembers(BigDecimal numberOfMembers) {
    
    this.numberOfMembers = numberOfMembers;
    return this;
  }

   /**
   * How many accounts are members of the DAO
   * @return numberOfMembers
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "How many accounts are members of the DAO")
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getNumberOfMembers() {
    return numberOfMembers;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumberOfMembers(BigDecimal numberOfMembers) {
    this.numberOfMembers = numberOfMembers;
  }


  public DaoFeed council(List<String> council) {
    
    this.council = council;
    return this;
  }

  public DaoFeed addCouncilItem(String councilItem) {
    this.council.add(councilItem);
    return this;
  }

   /**
   * List of accounts that can vote for various activity
   * @return council
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "List of accounts that can vote for various activity")
  @JsonProperty(JSON_PROPERTY_COUNCIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getCouncil() {
    return council;
  }


  @JsonProperty(JSON_PROPERTY_COUNCIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCouncil(List<String> council) {
    this.council = council;
  }


  public DaoFeed councilSeats(BigDecimal councilSeats) {
    
    this.councilSeats = councilSeats;
    return this;
  }

   /**
   * Council accounts count
   * @return councilSeats
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Council accounts count")
  @JsonProperty(JSON_PROPERTY_COUNCIL_SEATS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCouncilSeats() {
    return councilSeats;
  }


  @JsonProperty(JSON_PROPERTY_COUNCIL_SEATS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCouncilSeats(BigDecimal councilSeats) {
    this.councilSeats = councilSeats;
  }


  public DaoFeed policy(Policy policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Policy getPolicy() {
    return policy;
  }


  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolicy(Policy policy) {
    this.policy = policy;
  }


  public DaoFeed createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public DaoFeed totalProposalCount(BigDecimal totalProposalCount) {
    
    this.totalProposalCount = totalProposalCount;
    return this;
  }

   /**
   * Get totalProposalCount
   * @return totalProposalCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PROPOSAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTotalProposalCount() {
    return totalProposalCount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PROPOSAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalProposalCount(BigDecimal totalProposalCount) {
    this.totalProposalCount = totalProposalCount;
  }


  public DaoFeed activeProposalCount(BigDecimal activeProposalCount) {
    
    this.activeProposalCount = activeProposalCount;
    return this;
  }

   /**
   * Get activeProposalCount
   * @return activeProposalCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACTIVE_PROPOSAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getActiveProposalCount() {
    return activeProposalCount;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE_PROPOSAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActiveProposalCount(BigDecimal activeProposalCount) {
    this.activeProposalCount = activeProposalCount;
  }


  public DaoFeed totalDaoFunds(String totalDaoFunds) {
    
    this.totalDaoFunds = totalDaoFunds;
    return this;
  }

   /**
   * Get totalDaoFunds
   * @return totalDaoFunds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_DAO_FUNDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTotalDaoFunds() {
    return totalDaoFunds;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_DAO_FUNDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalDaoFunds(String totalDaoFunds) {
    this.totalDaoFunds = totalDaoFunds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DaoFeed daoFeed = (DaoFeed) o;
    return Objects.equals(this.transactionHash, daoFeed.transactionHash) &&
        Objects.equals(this.updateTransactionHash, daoFeed.updateTransactionHash) &&
        Objects.equals(this.createTimestamp, daoFeed.createTimestamp) &&
        Objects.equals(this.updateTimestamp, daoFeed.updateTimestamp) &&
        Objects.equals(this.id, daoFeed.id) &&
        Objects.equals(this.config, daoFeed.config) &&
        Objects.equals(this.metadata, daoFeed.metadata) &&
        Objects.equals(this.amount, daoFeed.amount) &&
        Objects.equals(this.totalSupply, daoFeed.totalSupply) &&
        Objects.equals(this.lastBountyId, daoFeed.lastBountyId) &&
        Objects.equals(this.lastProposalId, daoFeed.lastProposalId) &&
        Objects.equals(this.stakingContract, daoFeed.stakingContract) &&
        Objects.equals(this.numberOfAssociates, daoFeed.numberOfAssociates) &&
        Objects.equals(this.numberOfMembers, daoFeed.numberOfMembers) &&
        Objects.equals(this.council, daoFeed.council) &&
        Objects.equals(this.councilSeats, daoFeed.councilSeats) &&
        Objects.equals(this.policy, daoFeed.policy) &&
        Objects.equals(this.createdBy, daoFeed.createdBy) &&
        Objects.equals(this.totalProposalCount, daoFeed.totalProposalCount) &&
        Objects.equals(this.activeProposalCount, daoFeed.activeProposalCount) &&
        Objects.equals(this.totalDaoFunds, daoFeed.totalDaoFunds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionHash, updateTransactionHash, createTimestamp, updateTimestamp, id, config, metadata, amount, totalSupply, lastBountyId, lastProposalId, stakingContract, numberOfAssociates, numberOfMembers, council, councilSeats, policy, createdBy, totalProposalCount, activeProposalCount, totalDaoFunds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DaoFeed {\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    updateTransactionHash: ").append(toIndentedString(updateTransactionHash)).append("\n");
    sb.append("    createTimestamp: ").append(toIndentedString(createTimestamp)).append("\n");
    sb.append("    updateTimestamp: ").append(toIndentedString(updateTimestamp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    totalSupply: ").append(toIndentedString(totalSupply)).append("\n");
    sb.append("    lastBountyId: ").append(toIndentedString(lastBountyId)).append("\n");
    sb.append("    lastProposalId: ").append(toIndentedString(lastProposalId)).append("\n");
    sb.append("    stakingContract: ").append(toIndentedString(stakingContract)).append("\n");
    sb.append("    numberOfAssociates: ").append(toIndentedString(numberOfAssociates)).append("\n");
    sb.append("    numberOfMembers: ").append(toIndentedString(numberOfMembers)).append("\n");
    sb.append("    council: ").append(toIndentedString(council)).append("\n");
    sb.append("    councilSeats: ").append(toIndentedString(councilSeats)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    totalProposalCount: ").append(toIndentedString(totalProposalCount)).append("\n");
    sb.append("    activeProposalCount: ").append(toIndentedString(activeProposalCount)).append("\n");
    sb.append("    totalDaoFunds: ").append(toIndentedString(totalDaoFunds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

