/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import api.app.astrodao.com.openapi.models.Role;
import api.app.astrodao.com.openapi.models.VotePolicy;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Policy
 */
@JsonPropertyOrder({
  Policy.JSON_PROPERTY_DAO_ID,
  Policy.JSON_PROPERTY_PROPOSAL_BOND,
  Policy.JSON_PROPERTY_BOUNTY_BOND,
  Policy.JSON_PROPERTY_PROPOSAL_PERIOD,
  Policy.JSON_PROPERTY_BOUNTY_FORGIVENESS_PERIOD,
  Policy.JSON_PROPERTY_DEFAULT_VOTE_POLICY,
  Policy.JSON_PROPERTY_ROLES
})
@JsonTypeName("Policy")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class Policy {
  public static final String JSON_PROPERTY_DAO_ID = "daoId";
  private String daoId;

  public static final String JSON_PROPERTY_PROPOSAL_BOND = "proposalBond";
  private String proposalBond;

  public static final String JSON_PROPERTY_BOUNTY_BOND = "bountyBond";
  private String bountyBond;

  public static final String JSON_PROPERTY_PROPOSAL_PERIOD = "proposalPeriod";
  private BigDecimal proposalPeriod;

  public static final String JSON_PROPERTY_BOUNTY_FORGIVENESS_PERIOD = "bountyForgivenessPeriod";
  private BigDecimal bountyForgivenessPeriod;

  public static final String JSON_PROPERTY_DEFAULT_VOTE_POLICY = "defaultVotePolicy";
  private VotePolicy defaultVotePolicy;

  public static final String JSON_PROPERTY_ROLES = "roles";
  private List<Role> roles = new ArrayList<>();

  public Policy() { 
  }

  public Policy daoId(String daoId) {
    
    this.daoId = daoId;
    return this;
  }

   /**
   * Get daoId
   * @return daoId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDaoId() {
    return daoId;
  }


  @JsonProperty(JSON_PROPERTY_DAO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDaoId(String daoId) {
    this.daoId = daoId;
  }


  public Policy proposalBond(String proposalBond) {
    
    this.proposalBond = proposalBond;
    return this;
  }

   /**
   * Get proposalBond
   * @return proposalBond
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PROPOSAL_BOND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProposalBond() {
    return proposalBond;
  }


  @JsonProperty(JSON_PROPERTY_PROPOSAL_BOND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposalBond(String proposalBond) {
    this.proposalBond = proposalBond;
  }


  public Policy bountyBond(String bountyBond) {
    
    this.bountyBond = bountyBond;
    return this;
  }

   /**
   * Get bountyBond
   * @return bountyBond
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOUNTY_BOND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBountyBond() {
    return bountyBond;
  }


  @JsonProperty(JSON_PROPERTY_BOUNTY_BOND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBountyBond(String bountyBond) {
    this.bountyBond = bountyBond;
  }


  public Policy proposalPeriod(BigDecimal proposalPeriod) {
    
    this.proposalPeriod = proposalPeriod;
    return this;
  }

   /**
   * Get proposalPeriod
   * @return proposalPeriod
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PROPOSAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getProposalPeriod() {
    return proposalPeriod;
  }


  @JsonProperty(JSON_PROPERTY_PROPOSAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposalPeriod(BigDecimal proposalPeriod) {
    this.proposalPeriod = proposalPeriod;
  }


  public Policy bountyForgivenessPeriod(BigDecimal bountyForgivenessPeriod) {
    
    this.bountyForgivenessPeriod = bountyForgivenessPeriod;
    return this;
  }

   /**
   * Get bountyForgivenessPeriod
   * @return bountyForgivenessPeriod
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOUNTY_FORGIVENESS_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getBountyForgivenessPeriod() {
    return bountyForgivenessPeriod;
  }


  @JsonProperty(JSON_PROPERTY_BOUNTY_FORGIVENESS_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBountyForgivenessPeriod(BigDecimal bountyForgivenessPeriod) {
    this.bountyForgivenessPeriod = bountyForgivenessPeriod;
  }


  public Policy defaultVotePolicy(VotePolicy defaultVotePolicy) {
    
    this.defaultVotePolicy = defaultVotePolicy;
    return this;
  }

   /**
   * Get defaultVotePolicy
   * @return defaultVotePolicy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DEFAULT_VOTE_POLICY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VotePolicy getDefaultVotePolicy() {
    return defaultVotePolicy;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_VOTE_POLICY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDefaultVotePolicy(VotePolicy defaultVotePolicy) {
    this.defaultVotePolicy = defaultVotePolicy;
  }


  public Policy roles(List<Role> roles) {
    
    this.roles = roles;
    return this;
  }

  public Policy addRolesItem(Role rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Role> getRoles() {
    return roles;
  }


  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoles(List<Role> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Policy policy = (Policy) o;
    return Objects.equals(this.daoId, policy.daoId) &&
        Objects.equals(this.proposalBond, policy.proposalBond) &&
        Objects.equals(this.bountyBond, policy.bountyBond) &&
        Objects.equals(this.proposalPeriod, policy.proposalPeriod) &&
        Objects.equals(this.bountyForgivenessPeriod, policy.bountyForgivenessPeriod) &&
        Objects.equals(this.defaultVotePolicy, policy.defaultVotePolicy) &&
        Objects.equals(this.roles, policy.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daoId, proposalBond, bountyBond, proposalPeriod, bountyForgivenessPeriod, defaultVotePolicy, roles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Policy {\n");
    sb.append("    daoId: ").append(toIndentedString(daoId)).append("\n");
    sb.append("    proposalBond: ").append(toIndentedString(proposalBond)).append("\n");
    sb.append("    bountyBond: ").append(toIndentedString(bountyBond)).append("\n");
    sb.append("    proposalPeriod: ").append(toIndentedString(proposalPeriod)).append("\n");
    sb.append("    bountyForgivenessPeriod: ").append(toIndentedString(bountyForgivenessPeriod)).append("\n");
    sb.append("    defaultVotePolicy: ").append(toIndentedString(defaultVotePolicy)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

