/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import api.app.astrodao.com.openapi.models.Dao;
import api.app.astrodao.com.openapi.models.ProposalAction;
import api.app.astrodao.com.openapi.models.ProposalKindSwaggerDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Proposal
 */
@JsonPropertyOrder({
  Proposal.JSON_PROPERTY_TRANSACTION_HASH,
  Proposal.JSON_PROPERTY_UPDATE_TRANSACTION_HASH,
  Proposal.JSON_PROPERTY_CREATE_TIMESTAMP,
  Proposal.JSON_PROPERTY_UPDATE_TIMESTAMP,
  Proposal.JSON_PROPERTY_ID,
  Proposal.JSON_PROPERTY_PROPOSAL_ID,
  Proposal.JSON_PROPERTY_DAO_ID,
  Proposal.JSON_PROPERTY_DAO,
  Proposal.JSON_PROPERTY_PROPOSER,
  Proposal.JSON_PROPERTY_DESCRIPTION,
  Proposal.JSON_PROPERTY_STATUS,
  Proposal.JSON_PROPERTY_VOTE_STATUS,
  Proposal.JSON_PROPERTY_KIND,
  Proposal.JSON_PROPERTY_SUBMISSION_TIME,
  Proposal.JSON_PROPERTY_VOTE_COUNTS,
  Proposal.JSON_PROPERTY_VOTES,
  Proposal.JSON_PROPERTY_ACTIONS,
  Proposal.JSON_PROPERTY_COMMENTS_COUNT,
  Proposal.JSON_PROPERTY_VOTE_PERIOD_END
})
@JsonTypeName("Proposal")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class Proposal {
  public static final String JSON_PROPERTY_TRANSACTION_HASH = "transactionHash";
  private String transactionHash;

  public static final String JSON_PROPERTY_UPDATE_TRANSACTION_HASH = "updateTransactionHash";
  private String updateTransactionHash;

  public static final String JSON_PROPERTY_CREATE_TIMESTAMP = "createTimestamp";
  private BigDecimal createTimestamp;

  public static final String JSON_PROPERTY_UPDATE_TIMESTAMP = "updateTimestamp";
  private BigDecimal updateTimestamp;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_PROPOSAL_ID = "proposalId";
  private BigDecimal proposalId;

  public static final String JSON_PROPERTY_DAO_ID = "daoId";
  private String daoId;

  public static final String JSON_PROPERTY_DAO = "dao";
  private Dao dao;

  public static final String JSON_PROPERTY_PROPOSER = "proposer";
  private String proposer;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    INPROGRESS("InProgress"),
    
    APPROVED("Approved"),
    
    REJECTED("Rejected"),
    
    REMOVED("Removed"),
    
    EXPIRED("Expired"),
    
    MOVED("Moved");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  /**
   * Gets or Sets voteStatus
   */
  public enum VoteStatusEnum {
    ACTIVE("Active"),
    
    EXPIRED("Expired");

    private String value;

    VoteStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VoteStatusEnum fromValue(String value) {
      for (VoteStatusEnum b : VoteStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VOTE_STATUS = "voteStatus";
  private VoteStatusEnum voteStatus;

  public static final String JSON_PROPERTY_KIND = "kind";
  private ProposalKindSwaggerDto kind;

  public static final String JSON_PROPERTY_SUBMISSION_TIME = "submissionTime";
  private BigDecimal submissionTime;

  public static final String JSON_PROPERTY_VOTE_COUNTS = "voteCounts";
  private Object voteCounts;

  public static final String JSON_PROPERTY_VOTES = "votes";
  private Object votes;

  public static final String JSON_PROPERTY_ACTIONS = "actions";
  private List<ProposalAction> actions = new ArrayList<>();

  public static final String JSON_PROPERTY_COMMENTS_COUNT = "commentsCount";
  private BigDecimal commentsCount;

  public static final String JSON_PROPERTY_VOTE_PERIOD_END = "votePeriodEnd";
  private BigDecimal votePeriodEnd;

  public Proposal() { 
  }

  public Proposal transactionHash(String transactionHash) {
    
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionHash() {
    return transactionHash;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  public Proposal updateTransactionHash(String updateTransactionHash) {
    
    this.updateTransactionHash = updateTransactionHash;
    return this;
  }

   /**
   * Get updateTransactionHash
   * @return updateTransactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdateTransactionHash() {
    return updateTransactionHash;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTransactionHash(String updateTransactionHash) {
    this.updateTransactionHash = updateTransactionHash;
  }


  public Proposal createTimestamp(BigDecimal createTimestamp) {
    
    this.createTimestamp = createTimestamp;
    return this;
  }

   /**
   * Get createTimestamp
   * @return createTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreateTimestamp() {
    return createTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateTimestamp(BigDecimal createTimestamp) {
    this.createTimestamp = createTimestamp;
  }


  public Proposal updateTimestamp(BigDecimal updateTimestamp) {
    
    this.updateTimestamp = updateTimestamp;
    return this;
  }

   /**
   * Get updateTimestamp
   * @return updateTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getUpdateTimestamp() {
    return updateTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTimestamp(BigDecimal updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
  }


  public Proposal id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Proposal proposalId(BigDecimal proposalId) {
    
    this.proposalId = proposalId;
    return this;
  }

   /**
   * Get proposalId
   * @return proposalId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PROPOSAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getProposalId() {
    return proposalId;
  }


  @JsonProperty(JSON_PROPERTY_PROPOSAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposalId(BigDecimal proposalId) {
    this.proposalId = proposalId;
  }


  public Proposal daoId(String daoId) {
    
    this.daoId = daoId;
    return this;
  }

   /**
   * Get daoId
   * @return daoId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDaoId() {
    return daoId;
  }


  @JsonProperty(JSON_PROPERTY_DAO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDaoId(String daoId) {
    this.daoId = daoId;
  }


  public Proposal dao(Dao dao) {
    
    this.dao = dao;
    return this;
  }

   /**
   * Get dao
   * @return dao
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Dao getDao() {
    return dao;
  }


  @JsonProperty(JSON_PROPERTY_DAO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDao(Dao dao) {
    this.dao = dao;
  }


  public Proposal proposer(String proposer) {
    
    this.proposer = proposer;
    return this;
  }

   /**
   * Get proposer
   * @return proposer
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PROPOSER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProposer() {
    return proposer;
  }


  @JsonProperty(JSON_PROPERTY_PROPOSER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposer(String proposer) {
    this.proposer = proposer;
  }


  public Proposal description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Proposal status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public Proposal voteStatus(VoteStatusEnum voteStatus) {
    
    this.voteStatus = voteStatus;
    return this;
  }

   /**
   * Get voteStatus
   * @return voteStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VOTE_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VoteStatusEnum getVoteStatus() {
    return voteStatus;
  }


  @JsonProperty(JSON_PROPERTY_VOTE_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVoteStatus(VoteStatusEnum voteStatus) {
    this.voteStatus = voteStatus;
  }


  public Proposal kind(ProposalKindSwaggerDto kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProposalKindSwaggerDto getKind() {
    return kind;
  }


  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKind(ProposalKindSwaggerDto kind) {
    this.kind = kind;
  }


  public Proposal submissionTime(BigDecimal submissionTime) {
    
    this.submissionTime = submissionTime;
    return this;
  }

   /**
   * Get submissionTime
   * @return submissionTime
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUBMISSION_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSubmissionTime() {
    return submissionTime;
  }


  @JsonProperty(JSON_PROPERTY_SUBMISSION_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubmissionTime(BigDecimal submissionTime) {
    this.submissionTime = submissionTime;
  }


  public Proposal voteCounts(Object voteCounts) {
    
    this.voteCounts = voteCounts;
    return this;
  }

   /**
   * Get voteCounts
   * @return voteCounts
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VOTE_COUNTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getVoteCounts() {
    return voteCounts;
  }


  @JsonProperty(JSON_PROPERTY_VOTE_COUNTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVoteCounts(Object voteCounts) {
    this.voteCounts = voteCounts;
  }


  public Proposal votes(Object votes) {
    
    this.votes = votes;
    return this;
  }

   /**
   * Get votes
   * @return votes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VOTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getVotes() {
    return votes;
  }


  @JsonProperty(JSON_PROPERTY_VOTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVotes(Object votes) {
    this.votes = votes;
  }


  public Proposal actions(List<ProposalAction> actions) {
    
    this.actions = actions;
    return this;
  }

  public Proposal addActionsItem(ProposalAction actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProposalAction> getActions() {
    return actions;
  }


  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActions(List<ProposalAction> actions) {
    this.actions = actions;
  }


  public Proposal commentsCount(BigDecimal commentsCount) {
    
    this.commentsCount = commentsCount;
    return this;
  }

   /**
   * Get commentsCount
   * @return commentsCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COMMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCommentsCount() {
    return commentsCount;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCommentsCount(BigDecimal commentsCount) {
    this.commentsCount = commentsCount;
  }


  public Proposal votePeriodEnd(BigDecimal votePeriodEnd) {
    
    this.votePeriodEnd = votePeriodEnd;
    return this;
  }

   /**
   * Get votePeriodEnd
   * @return votePeriodEnd
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VOTE_PERIOD_END)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getVotePeriodEnd() {
    return votePeriodEnd;
  }


  @JsonProperty(JSON_PROPERTY_VOTE_PERIOD_END)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVotePeriodEnd(BigDecimal votePeriodEnd) {
    this.votePeriodEnd = votePeriodEnd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Proposal proposal = (Proposal) o;
    return Objects.equals(this.transactionHash, proposal.transactionHash) &&
        Objects.equals(this.updateTransactionHash, proposal.updateTransactionHash) &&
        Objects.equals(this.createTimestamp, proposal.createTimestamp) &&
        Objects.equals(this.updateTimestamp, proposal.updateTimestamp) &&
        Objects.equals(this.id, proposal.id) &&
        Objects.equals(this.proposalId, proposal.proposalId) &&
        Objects.equals(this.daoId, proposal.daoId) &&
        Objects.equals(this.dao, proposal.dao) &&
        Objects.equals(this.proposer, proposal.proposer) &&
        Objects.equals(this.description, proposal.description) &&
        Objects.equals(this.status, proposal.status) &&
        Objects.equals(this.voteStatus, proposal.voteStatus) &&
        Objects.equals(this.kind, proposal.kind) &&
        Objects.equals(this.submissionTime, proposal.submissionTime) &&
        Objects.equals(this.voteCounts, proposal.voteCounts) &&
        Objects.equals(this.votes, proposal.votes) &&
        Objects.equals(this.actions, proposal.actions) &&
        Objects.equals(this.commentsCount, proposal.commentsCount) &&
        Objects.equals(this.votePeriodEnd, proposal.votePeriodEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionHash, updateTransactionHash, createTimestamp, updateTimestamp, id, proposalId, daoId, dao, proposer, description, status, voteStatus, kind, submissionTime, voteCounts, votes, actions, commentsCount, votePeriodEnd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Proposal {\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    updateTransactionHash: ").append(toIndentedString(updateTransactionHash)).append("\n");
    sb.append("    createTimestamp: ").append(toIndentedString(createTimestamp)).append("\n");
    sb.append("    updateTimestamp: ").append(toIndentedString(updateTimestamp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    proposalId: ").append(toIndentedString(proposalId)).append("\n");
    sb.append("    daoId: ").append(toIndentedString(daoId)).append("\n");
    sb.append("    dao: ").append(toIndentedString(dao)).append("\n");
    sb.append("    proposer: ").append(toIndentedString(proposer)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    voteStatus: ").append(toIndentedString(voteStatus)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    submissionTime: ").append(toIndentedString(submissionTime)).append("\n");
    sb.append("    voteCounts: ").append(toIndentedString(voteCounts)).append("\n");
    sb.append("    votes: ").append(toIndentedString(votes)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    commentsCount: ").append(toIndentedString(commentsCount)).append("\n");
    sb.append("    votePeriodEnd: ").append(toIndentedString(votePeriodEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

