/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import api.app.astrodao.com.openapi.models.ReceiptAction;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Receipt
 */
@JsonPropertyOrder({
  Receipt.JSON_PROPERTY_RECEIPT_ID,
  Receipt.JSON_PROPERTY_PREDECESSOR_ACCOUNT_ID,
  Receipt.JSON_PROPERTY_RECEIVER_ACCOUNT_ID,
  Receipt.JSON_PROPERTY_ORIGINATED_FROM_TRANSACTION_HASH,
  Receipt.JSON_PROPERTY_INCLUDED_IN_BLOCK_TIMESTAMP,
  Receipt.JSON_PROPERTY_RECEIPT_ACTIONS
})
@JsonTypeName("Receipt")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class Receipt {
  public static final String JSON_PROPERTY_RECEIPT_ID = "receiptId";
  private String receiptId;

  public static final String JSON_PROPERTY_PREDECESSOR_ACCOUNT_ID = "predecessorAccountId";
  private String predecessorAccountId;

  public static final String JSON_PROPERTY_RECEIVER_ACCOUNT_ID = "receiverAccountId";
  private String receiverAccountId;

  public static final String JSON_PROPERTY_ORIGINATED_FROM_TRANSACTION_HASH = "originatedFromTransactionHash";
  private String originatedFromTransactionHash;

  public static final String JSON_PROPERTY_INCLUDED_IN_BLOCK_TIMESTAMP = "includedInBlockTimestamp";
  private BigDecimal includedInBlockTimestamp;

  public static final String JSON_PROPERTY_RECEIPT_ACTIONS = "receiptActions";
  private List<ReceiptAction> receiptActions = new ArrayList<>();

  public Receipt() { 
  }

  public Receipt receiptId(String receiptId) {
    
    this.receiptId = receiptId;
    return this;
  }

   /**
   * Get receiptId
   * @return receiptId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReceiptId() {
    return receiptId;
  }


  @JsonProperty(JSON_PROPERTY_RECEIPT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceiptId(String receiptId) {
    this.receiptId = receiptId;
  }


  public Receipt predecessorAccountId(String predecessorAccountId) {
    
    this.predecessorAccountId = predecessorAccountId;
    return this;
  }

   /**
   * Get predecessorAccountId
   * @return predecessorAccountId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PREDECESSOR_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPredecessorAccountId() {
    return predecessorAccountId;
  }


  @JsonProperty(JSON_PROPERTY_PREDECESSOR_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPredecessorAccountId(String predecessorAccountId) {
    this.predecessorAccountId = predecessorAccountId;
  }


  public Receipt receiverAccountId(String receiverAccountId) {
    
    this.receiverAccountId = receiverAccountId;
    return this;
  }

   /**
   * Get receiverAccountId
   * @return receiverAccountId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RECEIVER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReceiverAccountId() {
    return receiverAccountId;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceiverAccountId(String receiverAccountId) {
    this.receiverAccountId = receiverAccountId;
  }


  public Receipt originatedFromTransactionHash(String originatedFromTransactionHash) {
    
    this.originatedFromTransactionHash = originatedFromTransactionHash;
    return this;
  }

   /**
   * Get originatedFromTransactionHash
   * @return originatedFromTransactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORIGINATED_FROM_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOriginatedFromTransactionHash() {
    return originatedFromTransactionHash;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINATED_FROM_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginatedFromTransactionHash(String originatedFromTransactionHash) {
    this.originatedFromTransactionHash = originatedFromTransactionHash;
  }


  public Receipt includedInBlockTimestamp(BigDecimal includedInBlockTimestamp) {
    
    this.includedInBlockTimestamp = includedInBlockTimestamp;
    return this;
  }

   /**
   * Get includedInBlockTimestamp
   * @return includedInBlockTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_INCLUDED_IN_BLOCK_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getIncludedInBlockTimestamp() {
    return includedInBlockTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDED_IN_BLOCK_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIncludedInBlockTimestamp(BigDecimal includedInBlockTimestamp) {
    this.includedInBlockTimestamp = includedInBlockTimestamp;
  }


  public Receipt receiptActions(List<ReceiptAction> receiptActions) {
    
    this.receiptActions = receiptActions;
    return this;
  }

  public Receipt addReceiptActionsItem(ReceiptAction receiptActionsItem) {
    this.receiptActions.add(receiptActionsItem);
    return this;
  }

   /**
   * Get receiptActions
   * @return receiptActions
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ReceiptAction> getReceiptActions() {
    return receiptActions;
  }


  @JsonProperty(JSON_PROPERTY_RECEIPT_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceiptActions(List<ReceiptAction> receiptActions) {
    this.receiptActions = receiptActions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Receipt receipt = (Receipt) o;
    return Objects.equals(this.receiptId, receipt.receiptId) &&
        Objects.equals(this.predecessorAccountId, receipt.predecessorAccountId) &&
        Objects.equals(this.receiverAccountId, receipt.receiverAccountId) &&
        Objects.equals(this.originatedFromTransactionHash, receipt.originatedFromTransactionHash) &&
        Objects.equals(this.includedInBlockTimestamp, receipt.includedInBlockTimestamp) &&
        Objects.equals(this.receiptActions, receipt.receiptActions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiptId, predecessorAccountId, receiverAccountId, originatedFromTransactionHash, includedInBlockTimestamp, receiptActions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Receipt {\n");
    sb.append("    receiptId: ").append(toIndentedString(receiptId)).append("\n");
    sb.append("    predecessorAccountId: ").append(toIndentedString(predecessorAccountId)).append("\n");
    sb.append("    receiverAccountId: ").append(toIndentedString(receiverAccountId)).append("\n");
    sb.append("    originatedFromTransactionHash: ").append(toIndentedString(originatedFromTransactionHash)).append("\n");
    sb.append("    includedInBlockTimestamp: ").append(toIndentedString(includedInBlockTimestamp)).append("\n");
    sb.append("    receiptActions: ").append(toIndentedString(receiptActions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

