/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import api.app.astrodao.com.openapi.models.DaoResponse;
import api.app.astrodao.com.openapi.models.ProposalResponse;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SearchResultDto
 */
@JsonPropertyOrder({
  SearchResultDto.JSON_PROPERTY_DAOS,
  SearchResultDto.JSON_PROPERTY_PROPOSALS
})
@JsonTypeName("SearchResultDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class SearchResultDto {
  public static final String JSON_PROPERTY_DAOS = "daos";
  private DaoResponse daos;

  public static final String JSON_PROPERTY_PROPOSALS = "proposals";
  private ProposalResponse proposals;

  public SearchResultDto() { 
  }

  public SearchResultDto daos(DaoResponse daos) {
    
    this.daos = daos;
    return this;
  }

   /**
   * Get daos
   * @return daos
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAOS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DaoResponse getDaos() {
    return daos;
  }


  @JsonProperty(JSON_PROPERTY_DAOS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDaos(DaoResponse daos) {
    this.daos = daos;
  }


  public SearchResultDto proposals(ProposalResponse proposals) {
    
    this.proposals = proposals;
    return this;
  }

   /**
   * Get proposals
   * @return proposals
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PROPOSALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProposalResponse getProposals() {
    return proposals;
  }


  @JsonProperty(JSON_PROPERTY_PROPOSALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposals(ProposalResponse proposals) {
    this.proposals = proposals;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResultDto searchResultDto = (SearchResultDto) o;
    return Objects.equals(this.daos, searchResultDto.daos) &&
        Objects.equals(this.proposals, searchResultDto.proposals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daos, proposals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResultDto {\n");
    sb.append("    daos: ").append(toIndentedString(daos)).append("\n");
    sb.append("    proposals: ").append(toIndentedString(proposals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

