/*
 * Sputnik v2 API
 * Sputnik v2 API Backend Server
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.app.astrodao.com.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TransactionAction
 */
@JsonPropertyOrder({
  TransactionAction.JSON_PROPERTY_TRANSACTION_HASH,
  TransactionAction.JSON_PROPERTY_ACTION_KIND,
  TransactionAction.JSON_PROPERTY_ARGS
})
@JsonTypeName("TransactionAction")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-23T12:57:16.263593+02:00[Europe/Kiev]")
public class TransactionAction {
  public static final String JSON_PROPERTY_TRANSACTION_HASH = "transactionHash";
  private String transactionHash;

  /**
   * Gets or Sets actionKind
   */
  public enum ActionKindEnum {
    CREATEACCOUNT("CreateAccount"),
    
    DEPLOYCONTRACT("DeployContract"),
    
    FUNCTIONCALL("FunctionCall"),
    
    TRANSFER("Transfer"),
    
    STAKE("Stake"),
    
    ADDKEY("AddKey"),
    
    DELETEKEY("DeleteKey"),
    
    DELETEACCOUNT("DeleteAccount");

    private String value;

    ActionKindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionKindEnum fromValue(String value) {
      for (ActionKindEnum b : ActionKindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION_KIND = "actionKind";
  private ActionKindEnum actionKind;

  public static final String JSON_PROPERTY_ARGS = "args";
  private Object args;

  public TransactionAction() { 
  }

  public TransactionAction transactionHash(String transactionHash) {
    
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionHash() {
    return transactionHash;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  public TransactionAction actionKind(ActionKindEnum actionKind) {
    
    this.actionKind = actionKind;
    return this;
  }

   /**
   * Get actionKind
   * @return actionKind
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACTION_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionKindEnum getActionKind() {
    return actionKind;
  }


  @JsonProperty(JSON_PROPERTY_ACTION_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActionKind(ActionKindEnum actionKind) {
    this.actionKind = actionKind;
  }


  public TransactionAction args(Object args) {
    
    this.args = args;
    return this;
  }

   /**
   * Get args
   * @return args
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ARGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getArgs() {
    return args;
  }


  @JsonProperty(JSON_PROPERTY_ARGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArgs(Object args) {
    this.args = args;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionAction transactionAction = (TransactionAction) o;
    return Objects.equals(this.transactionHash, transactionAction.transactionHash) &&
        Objects.equals(this.actionKind, transactionAction.actionKind) &&
        Objects.equals(this.args, transactionAction.args);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionHash, actionKind, args);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionAction {\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    actionKind: ").append(toIndentedString(actionKind)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

