name: Build Test Image
on:
  workflow_dispatch:
  push:
    branches:
    - develop
    - main
    paths:
    - '.github/actions/test/Dockerfile'

jobs:
  build:
    name: Build Deploy
    env:
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.AWS_ECR_URL }}/jdk-near-cli
        tags: |
          type=raw,value=jdk-11-node-16
          type=raw,value=latest
          type=ref,event=branch,suffix=-latest
          type=sha,prefix=,format=long

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build And Push
      uses: docker/build-push-action@v2
      with:
        context: .github/actions/test
        file: .github/actions/test/Dockerfile
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        push: true
