name: Launch Autotests On Schedule
on:
  workflow_dispatch:
#  schedule:
#  - cron: '0 6 * * *'

jobs:
  run-autotests:
    name: Run Autotests
    uses: near-daos/astro-api-gateway/.github/workflows/run-autotests.yaml@develop
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEAR_ACCOUNT_ID: ${{ secrets.NEAR_ACCOUNT_ID }}
      NEAR_PUBLIC_KEY: ${{ secrets.NEAR_PUBLIC_KEY }}
      NEAR_PRIVATE_KEY: ${{ secrets.NEAR_PRIVATE_KEY }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
