name: Run Autotests
on:
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      environment:
        required: false
        default: develop
        description: Specify environment to run on. Valid values are develop, test
  workflow_call:
    inputs:
      environment:
        required: true
        description: Specify environment to run on. Valid values are develop, test
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
         required: true
      AWS_SECRET_ACCESS_KEY:
         required: true
      NEAR_ACCOUNT_ID:
         required: true
      NEAR_PUBLIC_KEY:
         required: true
      NEAR_PRIVATE_KEY:
         required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      id: set_environment
      run: |
        if [[ "${{ github.event.inputs.environment }}" != '' ]]
        then
          echo "Environment ${{ github.event.inputs.environment }} was provided manually"
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >>$GITHUB_ENV
          export ENVIRONMENT=${{ github.event.inputs.environment }}
        else
          echo "Environment ${{ inputs.environment }} was provided by parent workflow"
          echo "ENVIRONMENT=${{ inputs.environment }}" >>$GITHUB_ENV
          export ENVIRONMENT=${{ inputs.environment }}
        fi
        cat ".github/env.common" >>$GITHUB_ENV
        cat ".github/env.$ENVIRONMENT" >>$GITHUB_ENV
        echo "::set-output name=workflow_name::${GITHUB_WORKFLOW// /-}"
        echo "::set-output name=environment::${ENVIRONMENT}"

    - name: Execute Tests
      uses: ./.github/actions/test
      with:
        environment: ${{ steps.set_environment.outputs.environment }}
        env: ${{ env.TEST_ENV_NAME }}
        NEAR_ACCOUNT_ID: ${{ secrets.NEAR_ACCOUNT_ID }}
        NEAR_PUBLIC_KEY: ${{ secrets.NEAR_PUBLIC_KEY }}
        NEAR_PRIVATE_KEY: ${{ secrets.NEAR_PRIVATE_KEY }}

    - uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: test-framework/build/reports/tests/**

    - uses: actions/upload-artifact@v2
      with:
        name: allure_report
        path: test-framework/build/reports/allure-report/**

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: cp -n sputnik-v2-development test-framework/build/reports $(kubectl -n sputnik-v2-development  get pods --selector=app.kubernetes.io/instance=automation-report -o name):/app/${{ steps.set_environment.outputs.environment }}/${{ steps.set_environment.outputs.workflow_name }}-${{ github.run_number }}

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: cp -n sputnik-v2-development test-framework/build/reports/allure-report/history $(kubectl -n sputnik-v2-development  get pods --selector=app.kubernetes.io/instance=automation-report -o name):/app/${{ steps.set_environment.outputs.environment }}/history

    - name: Add Annotation
      run: |
        echo "::notice title=Allure Report::https://automation-report.app.astrodao.com/${{ steps.set_environment.outputs.environment }}/allure-report-${{ steps.set_environment.outputs.workflow_name }}-${{ github.run_number }}/allure-report/"
        echo "::notice title=History for Environment::https://automation-report.app.astrodao.com/${{ steps.set_environment.outputs.environment }}/"
