name: Run Autotests
on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: Specify environment to run on. Valid values are develop, test, staging, production

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
        if [[ "${{ github.event.inputs.environment }}" != '' ]]
        then
          echo "Environment ${{ github.event.inputs.environment }} was provided manually"
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >>$GITHUB_ENV
          export ENVIRONMENT=${{ github.event.inputs.environment }}
        else
          echo "Environment ${{ inputs.environment }} was provided by parent workflow"
          echo "ENVIRONMENT=${{ inputs.environment }}" >>$GITHUB_ENV
          export ENVIRONMENT=${{ inputs.environment }}
        fi
        cat ".github/env.common" >>$GITHUB_ENV
        cat ".github/env.$ENVIRONMENT" >>$GITHUB_ENV
    - name: Execute Tests
      uses: ./.github/actions/test
      with:
        environment: ${{ env.TEST_ENV_NAME }}
